### ISSUE TITLE
Update creep path after every tower placement

### ISSUE THREAD

**Issue by brad-richardson** [Diveafall/Fortify#2]

**Comment by brad-richardson** [comment]
I have now finished the updatePath() method for the creep. Now we just need to add temporary towers and make sure there is still a path and remove an added tower if they fail finding a new path.

**Comment by Diveafall** [comment]
When a tower is purchased, the following happens:
1. The tower is created
2. The tower is put inside the grid
3. `updatePath` is called on each creep and if one of them returns `false` everything cancels
4. If nothing bad happens the tower is pushed to the container

However, when I tried to block the path horizontally, the game crashed:
![screen shot 2016-04-13 at 7 45 41 pm](https://cloud.githubusercontent.com/assets/6404971/14514931/66dd679a-01b2-11e6-9684-fcfcb5b51358.png)

**Comment by brad-richardson** [comment]
I think I have it mostly fixed, I am still working on an issue with the towers where they aren't resetting availability of a space even after they are removed. (See image)
![screen shot 2016-04-14 at 2 21 32 pm](https://cloud.githubusercontent.com/assets/5924884/14542608/fa772bfe-024c-11e6-85a9-41e221afbf9b.png)

**Comment by brad-richardson** [comment]
Fixed
