### ISSUE TITLE
Creep Movement

### ISSUE THREAD

**Issue by Diveafall** [Diveafall/Fortify#8]
Sometimes after I add a tower (usually in the middle), a short time after moving the creep stops. All creeps spawning after it (starting from the same original location) stop as soon as they get on top of the problematic creep.

![creep_issue](https://cloud.githubusercontent.com/assets/6404971/14479331/8f27f504-00da-11e6-9709-ee8849d5092f.gif)

**Comment by brad-richardson** [comment]
Could you commit whatever code you are working with so I could try to fix this?

**Comment by Diveafall** [comment]
I will commit all the changes I've made so far this evening.

**Comment by Diveafall** [comment]
All the changes I've made so far have been committed.

**Comment by brad-richardson** [comment]
Fixed the bug
